import Link from 'next/link';
import { ArrowRight, Heart, Users, Globe2 } from 'lucide-react';

const milestones = [
  { year: '2001', title: 'A club takes root', text: 'Rotary Club of Kasthamandap begins with a simple commitment: make service part of everyday life.' },
  { year: '2010', title: 'Growing our reach', text: 'New partnerships help us bring education, health and clean water projects to more communities.' },
  { year: '2021', title: 'Responding together', text: 'Members, families and friends come together through the uncertainty of the pandemic.' },
  { year: '2026', title: 'Serving with soul', text: 'A new Rotary year invites us to lead with empathy, presence and purposeful action.' }
];

const images = ['/images/project-service.svg', '/images/project-youth.svg', '/images/project-fellowship.svg'];

export default function AboutPage() {
  return <>
    <section className="hero-banner"><div className="container-shell grid items-center gap-8 py-12 lg:grid-cols-[1fr_0.9fr]"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#F7A81B]">About Rotaract Club of Kasthamandap</p><h1 className="mt-4 max-w-2xl font-display leading-tight">A club built on <span className="text-[#F7A81B]">belonging.</span></h1><p className="mt-4 max-w-xl text-base leading-7 text-blue-100">The most lasting change starts with care for the person right in front of us.</p><p className="mt-4 text-sm text-blue-100">Home / About</p></div><img src={images[0]} alt="Placeholder community service" className="hidden aspect-[4/3] w-full rounded-xl object-cover lg:block" /></div></section>
    <section className="container-shell grid gap-12 py-20 sm:py-28 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">Our story</p><h2 className="mt-4 font-display text-3xl leading-tight text-[#17458F] sm:text-4xl">Service is not a separate part of life. It is how we choose to live it.</h2></div><div className="space-y-5 text-base leading-8 text-slate-600"><p>Rotary Club of Kasthamandap is a community of professionals, friends and neighbors connected by a practical optimism: when people listen well and work together, small acts can become meaningful progress.</p><p>As part of Rotary International District 3292, we create opportunities for service in Kathmandu and beyond. Our work spans education, health, clean water, youth development and fellowship.</p><p>We care about the outcome, but also about the way we get there: with humility, accountability and respect for the communities who know their own needs best.</p></div></section>
    <section className="bg-[#F5F7FA] py-16 md:py-20"><div className="container-shell"><div className="max-w-2xl"><p className="eyebrow">What connects us</p><h2 className="mt-4 font-display text-3xl text-[#17458F]">Three ways we show up.</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-7"><Heart className="text-[#F7A81B]" size={28} /><h3 className="mt-6 font-display text-xl text-[#17458F]">With compassion</h3><p className="mt-3 text-sm leading-7 text-slate-600">We start with listening, because good service responds to real people and real lives.</p></div><div className="rounded-xl border border-slate-200 bg-white p-7"><Users className="text-[#17458F]" size={28} /><h3 className="mt-6 font-display text-xl text-[#17458F]">With fellowship</h3><p className="mt-3 text-sm leading-7 text-slate-600">We make room for friendship, honest conversation and the joy of doing something together.</p></div><div className="rounded-xl border border-slate-200 bg-white p-7"><Globe2 className="text-[#17458F]" size={28} /><h3 className="mt-6 font-display text-xl text-[#17458F]">With purpose</h3><p className="mt-3 text-sm leading-7 text-slate-600">We turn shared energy into practical projects that strengthen our communities.</p></div></div></div></section>
    <section className="container-shell py-20 sm:py-28"><div className="grid gap-14 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="eyebrow">A few moments along the way</p><h2 className="mt-4 font-display text-3xl leading-tight text-[#17458F] sm:text-4xl">Twenty-five years of showing up.</h2></div><div className="border-l border-slate-200">{milestones.map((milestone) => <div key={milestone.year} className="relative border-b border-slate-200 pb-8 pl-8 pt-1 first:pt-0 last:border-0"><span className="absolute -left-[7px] top-0 h-3 w-3 rounded-full bg-[#F7A81B] ring-4 ring-white" /><p className="text-sm font-bold text-[#00A2E0]">{milestone.year}</p><h3 className="mt-2 font-display text-xl text-[#17458F]">{milestone.title}</h3><p className="mt-2 max-w-lg text-sm leading-7 text-slate-600">{milestone.text}</p></div>)}</div></div></section>
    <section className="container-shell grid gap-4 pb-20 sm:grid-cols-[1.2fr_0.8fr] sm:pb-28"><div className="h-72 rounded-3xl bg-cover bg-center sm:h-96" style={{ backgroundImage: `url(${images[1]})` }} /><div className="grid gap-4 sm:grid-rows-2"><div className="h-44 rounded-3xl bg-cover bg-center sm:h-auto" style={{ backgroundImage: `url(${images[2]})` }} /><div className="flex items-center rounded-3xl bg-[#17458F] p-7 text-white"><p className="font-display text-2xl leading-9">“Serve with Soul” is our invitation to make service feel human again.</p></div></div></section>
    <section className="bg-[#F7A81B] py-14"><div className="container-shell flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.12em] text-[#0d2d60]">Ready to meet the people behind the projects?</p><h2 className="mt-2 font-display text-3xl text-[#0d2d60]">There is a place for you here.</h2></div><Link href="/join" className="inline-flex items-center gap-2 font-bold text-[#0d2d60] underline underline-offset-4">Join the club <ArrowRight size={17} /></Link></div></section>
  </>;
}
