import Link from 'next/link';
import { ArrowRight, ChevronRight, HeartHandshake, Users } from 'lucide-react';
import { ArticleCard } from '@/components/ArticleCard';
import { MemberSpotlight } from '@/components/MemberSpotlight';
import { ProjectCard } from '@/components/ProjectCard';
import { gallery, members, messages, news, projects, site } from '@/data/site';

export default function Home() {
  const featured = projects.find((project) => project.featured) ?? projects[0];
  const spotlightMembers = members.filter((member) => member.group === 'BOD 2026/27').slice(0, 8);
  return <>
    <section className="relative min-h-[560px] overflow-hidden bg-[#0A2350] text-white"><img src="https://picsum.photos/seed/rck-hero-community/1600/900" alt="RCK volunteers at a community event" className="absolute inset-0 h-full w-full object-cover opacity-60" /><div className="absolute inset-0 bg-gradient-to-r from-[#0A2350]/95 via-[#0A2350]/65 to-[#0A2350]/20" /><div className="container-shell relative flex min-h-[560px] items-center py-16"><div className="max-w-2xl fade-up"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#F7A81B]">ROTARACT CLUB OF KASTHAMANDAP - RY 26/27</p><h1 className="mt-5 font-display text-5xl leading-tight sm:text-6xl">Service with <span className="text-[#F7A81B]">Soul.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-blue-50">We show up with care, curiosity and practical action for the communities around us.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/join" className="inline-flex items-center gap-2 rounded-full bg-[#F7A81B] px-6 py-3.5 font-bold text-[#0A2350]">Join Us <ArrowRight size={17} /></Link><Link href="/projects" className="inline-flex items-center gap-2 rounded-full border border-white/60 px-6 py-3.5 font-bold text-white">Explore Projects</Link><Link href="/donate" className="inline-flex items-center px-3 py-3.5 font-bold text-[#F7A81B]">Donate</Link></div></div></div><div className="absolute bottom-6 left-1/2 text-xs uppercase tracking-[0.18em] text-white/70">Scroll to explore</div></section>
    <section className="border-b border-slate-200 bg-white"><div className="container-shell grid grid-cols-2 divide-x divide-slate-200 sm:grid-cols-4">{site.impact.map((item) => <div key={item.label} className="px-4 py-8 text-center sm:py-10"><p className="font-display text-3xl text-[#17458F] sm:text-4xl">{item.value}</p><p className="mt-2 text-xs font-bold uppercase tracking-[0.1em] text-slate-500">{item.label}</p></div>)}</div></section>
    <section className="container-shell py-16 md:py-20"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">About RCK</p><h2 className="mt-3 font-display text-3xl text-[#17458F]">A little more care, in action.</h2></div><Link href="/about" className="hidden items-center gap-2 text-sm font-bold text-[#17458F] sm:flex">Read more <ArrowRight size={17} /></Link></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><img src="https://picsum.photos/seed/rck-about-service/1000/750" alt="Volunteers preparing a community service project" className="aspect-[4/3] w-full rounded-xl object-cover" /><img src="https://picsum.photos/seed/rck-about-youth/1000/750" alt="A bright reading space prepared for young learners" className="aspect-[4/3] w-full rounded-xl object-cover" /><div className="flex flex-col justify-center bg-[#F5F7FA] p-7"><p className="text-base leading-7 text-slate-600">We are a community of professionals, friends and neighbors connected by practical optimism and a belief in human-centered service.</p><Link href="/about" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#17458F] sm:hidden">Read more <ArrowRight size={16} /></Link></div></div></section>
    <section className="bg-[#F5F7FA] py-16 md:py-20"><div className="container-shell"><p className="eyebrow">Leadership voices</p><h2 className="mt-3 font-display text-3xl text-[#17458F]">Messages from our presidents.</h2><div className="mt-8 grid gap-6 lg:grid-cols-2">{messages.map((message) => <article key={message.name} className="grid gap-6 rounded-xl bg-white p-6 sm:grid-cols-[140px_1fr]"><img src={message.image} alt="Placeholder portrait" className="aspect-square w-full rounded-lg object-cover" /><div><p className="text-[#F7A81B]">“</p><p className="text-sm leading-7 text-slate-600">{message.message}</p><p className="mt-4 font-bold text-[#0A2350]">{message.name}</p><p className="text-xs text-[#17458F]">{message.title}</p></div></article>)}</div></div></section>
    <section className="container-shell py-16 md:py-20"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Projects</p><h2 className="mt-3 font-display text-3xl text-[#17458F]">Turning good intentions into action.</h2></div><Link href="/projects" className="flex items-center gap-2 text-sm font-bold text-[#17458F]">View all <ArrowRight size={17} /></Link></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.25fr_1fr_1fr]"><Link href={`/projects/${featured.id}`} className="relative overflow-hidden rounded-xl bg-[#17458F] text-white lg:row-span-2"><img src={featured.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45" /><div className="relative flex min-h-[360px] flex-col justify-end p-7"><span className="w-fit rounded-full bg-[#F7A81B] px-3 py-1 text-xs font-bold uppercase text-[#0A2350]">Flagship</span><h3 className="mt-4 font-display text-2xl">{featured.title}</h3><p className="mt-3 text-sm leading-6 text-blue-50">{featured.summary}</p></div></Link>{projects.filter((project) => !project.featured).slice(0, 3).map((project) => <ProjectCard key={project.id} project={project} />)}</div></section>
    <section className="bg-[#F5F7FA] py-16 md:py-20"><div className="container-shell"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Gallery</p><h2 className="mt-3 font-display text-3xl text-[#17458F]">Moments that stay with us.</h2></div><Link href="/gallery" className="flex items-center gap-2 text-sm font-bold text-[#17458F]">View all <ArrowRight size={17} /></Link></div><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-3">{gallery.slice(0, 6).map((item) => <Link key={item.id} href="/gallery"><img src={item.image} alt={item.title} className="aspect-[4/3] w-full rounded-xl object-cover" /></Link>)}</div></div></section>
    <section className="container-shell py-16 md:py-20"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Members</p><h2 className="mt-3 font-display text-3xl text-[#17458F]">The people behind the work.</h2></div><Link href="/members" className="hidden items-center gap-2 text-sm font-bold text-[#17458F] sm:flex">Meet everyone <ArrowRight size={17} /></Link></div><MemberSpotlight members={spotlightMembers} /></section>
    <section className="bg-[#F5F7FA] py-16 md:py-20"><div className="container-shell"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">News & Articles</p><h2 className="mt-3 font-display text-3xl text-[#17458F]">Notes from our community.</h2></div><Link href="/news" className="flex items-center gap-2 text-sm font-bold text-[#17458F]">View all <ArrowRight size={17} /></Link></div><div className="mt-8 grid gap-8 md:grid-cols-3">{news.slice(0, 3).map((article) => <ArticleCard key={article.id} article={article} />)}</div></div></section>
    <section className="container-shell py-16 md:py-20"><div className="grid gap-8 rounded-xl bg-[#17458F] p-8 text-white sm:p-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-3"><HeartHandshake className="text-[#F7A81B]" size={24} /><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#F7A81B]">Rotary FAQ quiz</p></div><h2 className="mt-4 font-display text-3xl">Ten questions. A better sense of what we do.</h2></div><Link href="/quiz" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#F7A81B] px-6 py-3.5 font-bold text-[#0A2350]">Take the quiz <ChevronRight size={18} /></Link></div></section>
    <section className="bg-[#F7A81B] py-8"><div className="container-shell flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3 text-[#0A2350]"><Users size={22} /><p className="font-bold">Bring your curiosity. Leave a little more connected.</p></div><div className="flex gap-5"><Link href="/join" className="font-bold text-[#0A2350] underline">Join Us</Link><Link href="/donate" className="font-bold text-[#0A2350] underline">Donate</Link></div></div></section>
    <section className="container-shell grid gap-8 py-16 md:grid-cols-2 md:py-20"><div><p className="eyebrow">Contact</p><h2 className="mt-3 font-display text-3xl text-[#17458F]">Start a conversation.</h2><p className="mt-4 max-w-md text-base leading-7 text-slate-600">Have a project idea or membership question? Write to <a href={`mailto:${site.contact.email}`} className="font-bold text-[#17458F]">{site.contact.email}</a>.</p></div><iframe title="Map of Kathmandu" src={site.contact.map} className="h-64 w-full rounded-xl border-0" loading="lazy" /></section>
  </>;
}
