'use client';

import { HeartHandshake } from 'lucide-react';
import { useState } from 'react';
import { projects } from '@/data/site';

const funds = ['General Fund', ...projects.slice(0, 3).map((project) => project.title), 'Other'];

export default function DonatePage() {
	const [submitted, setSubmitted] = useState(false);
	const [form, setForm] = useState({ name: '', contact: '', purpose: funds[0], amount: '', message: '' });
	const updateField = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
	const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
		event.preventDefault();
		// Replace this client-side step with the club's backend or payment API when ready.
		setSubmitted(true);
		window.setTimeout(() => document.getElementById('qr-code')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0);
	};
	return <section className="container-shell py-16 sm:py-24"><div className="mx-auto max-w-4xl"><p className="eyebrow">Support the work</p><h1 className="mt-5 max-w-3xl font-display text-4xl leading-tight text-[#17458F] sm:text-6xl">Small acts can carry a long way.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">Your contribution helps local partners turn good ideas into practical service, from compassionate care to clean water and joyful learning spaces.</p><div className="mt-8 flex items-center gap-3 text-sm font-bold text-[#17458F]"><HeartHandshake className="text-[#F7A81B]" /> Thank you for serving with us.</div>
		<form onSubmit={handleSubmit} className="mt-12 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-9"><h2 className="font-display text-2xl text-[#17458F]">Tell us how you would like to help</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold text-[#0A2350]">Full Name <span className="text-[#F7A81B]">*</span><input required value={form.name} onChange={(event) => updateField('name', event.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 px-4 py-3 font-normal outline-none focus:border-[#17458F]" /></label><label className="text-sm font-bold text-[#0A2350]">Email or Phone <span className="text-[#F7A81B]">*</span><input required value={form.contact} onChange={(event) => updateField('contact', event.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 px-4 py-3 font-normal outline-none focus:border-[#17458F]" /></label><label className="text-sm font-bold text-[#0A2350]">Purpose / Fund<select value={form.purpose} onChange={(event) => updateField('purpose', event.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-[#17458F]">{funds.map((fund) => <option key={fund}>{fund}</option>)}</select></label><label className="text-sm font-bold text-[#0A2350]">Amount <span className="font-normal text-slate-500">(optional)</span><input value={form.amount} onChange={(event) => updateField('amount', event.target.value)} placeholder="e.g. NPR 2,000" className="mt-2 w-full rounded-lg border border-slate-200 px-4 py-3 font-normal outline-none focus:border-[#17458F]" /></label><label className="text-sm font-bold text-[#0A2350] sm:col-span-2">Message <span className="font-normal text-slate-500">(optional)</span><textarea value={form.message} onChange={(event) => updateField('message', event.target.value)} rows={4} className="mt-2 w-full rounded-lg border border-slate-200 px-4 py-3 font-normal outline-none focus:border-[#17458F]" /></label></div><button type="submit" className="mt-7 rounded-full bg-[#F7A81B] px-6 py-3.5 font-bold text-[#0A2350] transition hover:bg-[#0A2350] hover:text-white">Continue to Payment</button></form>
		{submitted && <section id="qr-code" className="mt-10 scroll-mt-28 rounded-2xl bg-[#0A2350] p-7 text-white sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#F7A81B]">Next step</p><h2 className="mt-3 font-display text-2xl">Your donation details are ready.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-blue-100">Confirm the details below, then scan to donate via the club&apos;s verified payment method.</p><div className="mt-7 grid gap-8 sm:grid-cols-[180px_1fr] sm:items-center"><div className="grid aspect-square place-items-center rounded-xl bg-white p-4 text-center text-[#17458F]"><div className="grid h-full w-full place-items-center border-4 border-dashed border-[#F7A81B] font-bold">QR CODE</div></div><div className="text-sm leading-7 text-blue-100"><p className="text-lg font-bold text-white">Scan to donate via mobile payment</p><dl className="mt-4 space-y-2"><div className="flex gap-2"><dt className="font-bold text-[#F7A81B]">Name:</dt><dd>{form.name}</dd></div><div className="flex gap-2"><dt className="font-bold text-[#F7A81B]">Purpose:</dt><dd>{form.purpose}</dd></div>{form.amount && <div className="flex gap-2"><dt className="font-bold text-[#F7A81B]">Amount:</dt><dd>{form.amount}</dd></div>}</dl></div></div></section>}
		</div></section>;
}
