import Link from 'next/link';
import { ArrowLeft, CalendarDays, MapPin, Share2, Users } from 'lucide-react';
import { notFound } from 'next/navigation';
import { projects } from '@/data/site';

export function generateStaticParams() { return projects.map((project) => ({ id: project.id })); }

export default async function ProjectDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const project = projects.find((item) => item.id === id);
  if (!project) notFound();
  return <>
    <section className="bg-[#0d2d60] py-14 text-white"><div className="container-shell"><Link href="/projects" className="inline-flex items-center gap-2 text-sm font-bold text-blue-100 hover:text-[#F7A81B]"><ArrowLeft size={16} /> Back to projects</Link><div className="mt-12 max-w-3xl"><span className="rounded-full bg-[#F7A81B] px-3 py-1 text-xs font-bold uppercase tracking-[0.1em] text-[#0d2d60]">{project.avenue} · {project.status}</span><h1 className="mt-6 font-display text-4xl leading-tight sm:text-6xl">{project.title}</h1><p className="mt-6 text-lg leading-8 text-blue-100">{project.summary}</p></div></div></section>
    <section className="container-shell grid gap-12 py-16 sm:py-24 lg:grid-cols-[1.2fr_0.8fr]"><div><div className="h-72 rounded-3xl bg-cover bg-center sm:h-[480px]" style={{ backgroundImage: `url(${project.image})` }} /><div className="mt-10 space-y-5 text-base leading-8 text-slate-600"><p>Every project begins with a conversation. For {project.title}, our members are working alongside local partners to understand what would make the biggest difference and how the community can shape the work from the beginning.</p><p>This project is part of Rotary Club of Kasthamandap’s wider commitment to practical, lasting service. We will share updates here as the work develops and invite members, partners and supporters to be part of the journey.</p></div></div><aside className="h-fit rounded-2xl bg-[#f2f7fb] p-7 sm:p-9"><p className="eyebrow">Project details</p><dl className="mt-7 space-y-6"><div className="flex gap-4"><CalendarDays className="shrink-0 text-[#00A2E0]" size={21} /><div><dt className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Date</dt><dd className="mt-1 text-sm font-bold text-[#17458F]">{new Date(project.date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</dd></div></div><div className="flex gap-4"><MapPin className="shrink-0 text-[#00A2E0]" size={21} /><div><dt className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Location</dt><dd className="mt-1 text-sm font-bold text-[#17458F]">{project.location}</dd></div></div><div className="flex gap-4"><Users className="shrink-0 text-[#00A2E0]" size={21} /><div><dt className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">Beneficiaries</dt><dd className="mt-1 text-sm font-bold text-[#17458F]">Community partners and families</dd></div></div></dl><div className="mt-8 border-t border-slate-200 pt-6"><p className="flex items-center gap-2 text-sm font-bold text-[#17458F]"><Share2 size={16} /> Share this project</p><div className="mt-4 flex gap-2"><button className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-600 hover:border-[#17458F]">Facebook</button><button className="rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-600 hover:border-[#17458F]">WhatsApp</button></div></div></aside></section>
  </>;
}
