'use client';

import { Search, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { members } from '@/data/site';

const tabs = ['BOD 2026/27', 'General Members', 'Past Presidents', 'Major Donors'];
type Profile = { id: string; name: string; role: string; group: string; bio: string; image: string; memberSince: string; profession: string; organization: string; achievements: string[]; interests: string; showContact: boolean; email: string; phone: string };

const normalize = (member: { id: string; name: string; role: string; group: string; bio: string; image: string }): Profile => ({ ...member, memberSince: '2026', profession: 'Placeholder professional', organization: 'Placeholder Organization', achievements: ['Participated in a service activity', 'Joined a fellowship gathering', 'Supported a club initiative'], interests: 'Service, learning and fellowship', showContact: false, email: '', phone: '' });

export default function MembersPage() {
  const [tab, setTab] = useState(tabs[0]);
  const [query, setQuery] = useState('');
  const [tabBeforeSearch, setTabBeforeSearch] = useState(tabs[0]);
  const [selected, setSelected] = useState<Profile | null>(null);
  const lastFocused = useRef<HTMLButtonElement | null>(null);
  const visible = members.filter((member) => (!query.trim() ? member.group === tab : true) && `${member.name} ${member.role} ${member.bio}`.toLowerCase().includes(query.toLowerCase())).map(normalize);
  useEffect(() => { if (query.trim() && tab !== tabs[0]) { setTabBeforeSearch(tab); setTab(tabs[0]); } if (!query.trim() && tab === tabs[0] && tabBeforeSearch !== tabs[0]) setTab(tabBeforeSearch); }, [query, tab, tabBeforeSearch]);
  useEffect(() => { if (!selected) return; const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') setSelected(null); }; document.body.style.overflow = 'hidden'; document.addEventListener('keydown', onKeyDown); return () => { document.body.style.overflow = ''; document.removeEventListener('keydown', onKeyDown); lastFocused.current?.focus(); }; }, [selected]);
  return <>
    <section className="hero-banner"><div className="container-shell py-12"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#F7A81B]">The people of RCK</p><h1 className="mt-4 max-w-3xl font-display leading-tight">Service has many faces. <span className="text-[#F7A81B]">Here are ours.</span></h1><p className="mt-4 max-w-xl text-base leading-7 text-blue-100">Meet the people who bring their time, ideas and care to Rotaract Club of Kasthamandap.</p><p className="mt-4 text-sm text-blue-100">Home / Members</p></div></section>
    <section className="container-shell py-16 md:py-20"><div className="flex flex-col gap-5 border-b border-slate-200 pb-7 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-full border px-4 py-2 text-sm font-bold ${tab === item ? 'border-[#17458F] bg-[#17458F] text-white' : 'border-slate-200 text-slate-600'}`}>{item}</button>)}</div><div className="relative w-full lg:w-64"><Search className="absolute left-3 top-3 text-slate-400" size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search members" aria-label="Search members" className="w-full rounded-full border border-slate-200 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-[#17458F]" /></div></div><div className="grid gap-6 pt-9 sm:grid-cols-2 lg:grid-cols-4">{visible.map((member) => <button key={member.id} onClick={(event) => { lastFocused.current = event.currentTarget; setSelected(member); }} className="group overflow-hidden rounded-xl border border-slate-200 bg-white text-left transition hover:-translate-y-1 hover:shadow-lg"><img src={member.image} alt="Placeholder avatar" className="aspect-square w-full object-cover" /><div className="p-5"><p className="text-xs font-bold uppercase tracking-[0.1em] text-[#17458F]">{member.role}</p><h2 className="mt-2 font-display text-lg text-[#0A2350]">{member.name}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{member.bio}</p></div></button>)}</div>{visible.length === 0 && <p className="py-20 text-center text-slate-500">No members match this search.</p>}</section>
    {selected && <div role="dialog" aria-modal="true" aria-label="Member profile" onClick={(event) => { if (event.target === event.currentTarget) setSelected(null); }} className="fixed inset-0 z-[60] overflow-y-auto bg-[#0A2350]/90 p-4 sm:p-8"><div className="relative mx-auto mt-8 max-w-2xl rounded-xl bg-white p-6 shadow-2xl sm:mt-16 sm:p-9"><button aria-label="Close member profile" onClick={() => setSelected(null)} className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-[#F5F7FA] text-[#0A2350]"><X /></button><div className="grid gap-7 sm:grid-cols-[180px_1fr]"><img src={selected.image} alt="Placeholder avatar" className="aspect-square w-full rounded-lg object-cover" /><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#17458F]">{selected.role}</p><h2 className="mt-2 font-display text-2xl text-[#0A2350]">{selected.name}</h2><p className="mt-3 text-sm text-slate-600">Member since {selected.memberSince} · {selected.profession} at {selected.organization}</p><p className="mt-4 text-sm leading-6 text-slate-600">{selected.interests}</p></div></div><div className="mt-7 border-t border-slate-200 pt-6"><h3 className="font-bold text-[#17458F]">Achievements</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-slate-600">{selected.achievements.map((achievement) => <li key={achievement}>{achievement}</li>)}</ul>{selected.showContact && <div className="mt-6 border-t border-slate-200 pt-5 text-sm text-slate-600"><p className="font-bold text-[#0A2350]">Contact</p><p className="mt-2">{selected.email} · {selected.phone}</p><p className="mt-1">Social links: placeholder profile</p></div>}</div></div></div>}
  </>;
}
